### ISSUE TITLE
Fix automatic language redirection

### ISSUE THREAD

**Issue by victorbnl** [colabois/colabois.fr#2]

**Comment by SuwakoMmh** [comment]
We could keep the index page for redirection and use another one for the actual front page :
it won't break as soon as user click a link because no page will link to the real index, but only to the front page.

Would this work ?

**Comment by victorbnl** [comment]
No. We cannot use a custom index page, the index page will always be the default one : English.

The solution to that would be to set no default language but I don't even know if it's possible, but anyway doing that would break redirection for untranslated pages

**Comment by SuwakoMmh** [comment]
I mean : we can move the front page elsewhere and use the index page (for all languages) as a redirect to the front page

**Comment by victorbnl** [comment]
It doesn't seem that clean to me but thanks for your suggestion, I'll see what I can do

**Comment by victorbnl** [comment]
I found a solution creating a new "redirect" language. The problem is that we loose the default language fallback so if the page doesn't exist in "redirect" but exist in both english and spanish, it may redirect randomly in either english or spanish, we can't know

**Comment by victorbnl** [comment]
Or we could just use a more classic language system which has no fallback at all. I mean, if a page doesn't exist in frnehc and you are french, you don't want to see this page in english or spanish, so a 404 makes more sense I think

**Comment by SuwakoMmh** [comment]
There shouldn't be any link to a non existant page so a 404 doesn't seem like a problem to me

**Comment by victorbnl** [comment]
100% true, I'll do so then!
